In [ ]:
f=lambda x,y: x if x==y else r=y for i in range

In [2]:
f=lambda a,b: max(j for j in range(1,min(a,b)+1)if(a%j==0 and b%j==0))

In [3]:
f(17,27)

1

In [4]:
def mygen():
    yield 10
    
    yield 20
    
    yield 30

In [8]:
f=mygen()

In [11]:
next(f)

10

In [12]:
import numpy as np

In [13]:
x=[[1,2,3],[4,5,6]]

In [14]:
x+x

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [15]:
e=np.array(x)

In [16]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
e[0,0]

1

In [18]:
e[0][0]

1

In [24]:
e
e.flags.writeable=False
e[0][0]=90

ValueError: assignment destination is read-only

In [26]:
e=np.zeros((4,5))
e[:,0:2]=1
e

array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [27]:
e=np.zeros((4,5))
e[:,0::2]=1
e

array([[1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1.]])

In [28]:
e=np.zeros((4,5))
e[:,1:2]=1
e

array([[0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [32]:
e=np.zeros((4,5))
e[1:,1::2]=1
e

array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.]])

In [30]:
e=np.zeros((4,5))
e[:,:2]=1
e

array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [47]:

e=np.zeros((4,5),dtype=int)
e[0::2,0::2]=1
e

array([[1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0]])

In [71]:
e=np.zeros((8,8))
e


array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [83]:
e=np.ones((8,8))
e[0::2,0::2]=0
e

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [62]:
e[:0,:0]=0
e

array([[0., 0., 0., 1., 0., 1., 0., 1.],
       [0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [84]:
e=np.ones((8,8))
e[0::2,0::2]=0
e[1::2,1::2]=0
print(e)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [85]:
e.T

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

NameError: name 'unicode' is not defined